language: cpp
compiler:
  - gcc
before_install:
  - wget https://github.com/cpputest/cpputest.github.io/blob/master/releases/cpputest-3.4.tar.gz?raw=true
  - tar xvzf cpputest-3.4.tar.gz
  - cd cpputest-3.4
  - ./configure --disable-maintainer-mode
  - make
  - make install
  - sudo add-apt-repository ppa:codegear/release -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:dns/gnu -y
  - sudo add-apt-repository ppa:ondrej/php5-experimental -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq libevent-dev libtag1-dev nettle-dev libdb++-dev premake4 gcc-4.8 g++-4.8 libjson-c-dev
before_script:
  - cd build/
  - premake4 gmake
  - make CXX=g++-4.8
script: ./bin/newsoul-tests
branches:
  only:
    - master
